server:
  port: 8082 # IMPORTANT : Port 8082 (car 8081 est pris par Order Service)

spring:
  application:
    name: fleet-service
  
  datasource:
    # On se connecte au port 5435 (celui défini dans docker-compose pour fleet-db)
    url: jdbc:postgresql://localhost:5435/fleet_db
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update # Crée la table 'driver' automatiquement
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true